# Generated by Django 4.2.6 on 2024-05-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='neighbourhood',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_photo1',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_photo2',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_photo3',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_photo4',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
