# Generated by Django 4.2.6 on 2024-05-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertydetails_neighbourhood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
